installNamespace: open-cluster-management

hypershiftAddonMgr:
  deploymentName: hypershift-addon-manager
  serviceaccount: hypershift-addon-manager-sa
  image: quay.io/ianzhang366/hypershift-addon-operator:latest


hypershiftDeployment:
  deploymentName: hypershift-deployment-controller
  serviceaccount: hyc
  leaderRoleName: hypershiftDeployment-leader-election
  editorRoleName: hypershiftdeployment-editor-role
  viewerRoleName: hypershiftdeployment-viewer-role

global:
  imageOverrides:
    hypershift_deployment_controller: quay.io/stolostron/hypershift-deployment-controller:latest
  pullSecret: ""
  namespace: default
hubconfig:
  nodeSelector: {}
  proxyConfigs: {}
  replicaCount: 2
  tolerations: []
org: open-cluster-management