# permissions for end users to view hypershiftdeployment.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.hypershiftDeployment.viewerRoleName }}
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - hypershiftdeployment
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - hypershiftdeployment/status
  verbs:
  - get
