kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.org }}:{{ .Chart.Name }}:{{ .Values.hypershiftAddonMgrOperator.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Chart.Name }}:{{ .Values.hypershiftAddonMgrOperator.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.hypershiftAddonMgrOperator.serviceaccount }}
    namespace: {{ .Values.global.namespace }}
